### ISSUE TITLE
ubuntu 20.04 galactic 好多代码都编译不过去，比如：colcon build  --packages-up-to behavior_tree

### ISSUE THREAD

**Issue by dabaitunaitaang** [duyongquan/ROS2-OpenRoboticsToolkit#2]
m@ubun:~/ros2_tutorials_ws$ colcon build  --packages-up-to behavior_tree

Starting >>> behavior_tree
--- stderr: behavior_tree                             
In file included from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/plugins/action/spin_action.hpp:6,
                 from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/plugins/action/spin_action.cpp:4:
/home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/bt_action_node.hpp: In constructor ‘ros2_tutorials::behavior_tree::BtActionNode<ActionT>::BtActionNode(const string&, const string&, const BT::NodeConfiguration&)’:
/home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/bt_action_node.hpp:40:12: error: no matching function for call to ‘rclcpp::Node::create_callback_group(rclcpp::CallbackGroupType, bool)’
   40 |       false);
      |            ^
In file included from /opt/ros/foxy/include/rclcpp/executors/single_threaded_executor.hpp:28,
                 from /opt/ros/foxy/include/rclcpp/executors.hpp:22,
                 from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:146,
                 from /opt/ros/foxy/include/nav2_util/node_utils.hpp:19,
                 from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/bt_action_node.hpp:8,
                 from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/plugins/action/spin_action.hpp:6,
                 from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/plugins/action/spin_action.cpp:4:
/opt/ros/foxy/include/rclcpp/node.hpp:144:3: note: candidate: ‘rclcpp::CallbackGroup::SharedPtr rclcpp::Node::create_callback_group(rclcpp::CallbackGroupType)’
  144 |   create_callback_group(rclcpp::CallbackGroupType group_type);
      |   ^~~~~~~~~~~~~~~~~~~~~
/opt/ros/foxy/include/rclcpp/node.hpp:144:3: note:   candidate expects 1 argument, 2 provided
In file included from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/plugins/action/spin_action.hpp:6,
                 from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/plugins/action/spin_action.cpp:4:
/home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/bt_action_node.hpp:41:30: error: ‘class rclcpp::executors::SingleThreadedExecutor’ has no member named ‘add_callback_group’
   41 |     callback_group_executor_.add_callback_group(callback_group_, node_->get_node_base_interface());
      |                              ^~~~~~~~~~~~~~~~~~
In file included from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/plugins/action/back_up_action.hpp:6,
                 from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/plugins/action/back_up_action.cpp:4:
/home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/bt_action_node.hpp: In constructor ‘ros2_tutorials::behavior_tree::BtActionNode<ActionT>::BtActionNode(const string&, const string&, const BT::NodeConfiguration&)’:
/home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/bt_action_node.hpp:40:12: error: no matching function for call to ‘rclcpp::Node::create_callback_group(rclcpp::CallbackGroupType, bool)’
   40 |       false);
      |            ^
In file included from /opt/ros/foxy/include/rclcpp/executors/single_threaded_executor.hpp:28,
                 from /opt/ros/foxy/include/rclcpp/executors.hpp:22,
                 from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:146,
                 from /opt/ros/foxy/include/nav2_util/node_utils.hpp:19,
                 from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/bt_action_node.hpp:8,
                 from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/plugins/action/back_up_action.hpp:6,
                 from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/plugins/action/back_up_action.cpp:4:
/opt/ros/foxy/include/rclcpp/node.hpp:144:3: note: candidate: ‘rclcpp::CallbackGroup::SharedPtr rclcpp::Node::create_callback_group(rclcpp::CallbackGroupType)’
  144 |   create_callback_group(rclcpp::CallbackGroupType group_type);
      |   ^~~~~~~~~~~~~~~~~~~~~
/opt/ros/foxy/include/rclcpp/node.hpp:144:3: note:   candidate expects 1 argument, 2 provided
In file included from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/plugins/action/back_up_action.hpp:6,
                 from /home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/plugins/action/back_up_action.cpp:4:
/home/m/ros2_tutorials_ws/src/ros2_tutorials/navigation/behavior_tree/include/behavior_tree/bt_action_node.hpp:41:30: error: ‘class rclcpp::executors::SingleThreadedExecutor’ has no member named ‘add_callback_group’
   41 |     callback_group_executor_.add_callback_group(callback_group_, node_->get_node_base_interface());
      |                              ^~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/spin_action_bt_node.dir/build.make:63：CMakeFiles/spin_action_bt_node.dir/plugins/action/spin_action.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:426：CMakeFiles/spin_action_bt_node.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
make[2]: *** [CMakeFiles/back_up_action_bt_node.dir/build.make:63：CMakeFiles/back_up_action_bt_node.dir/plugins/action/back_up_action.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:561：CMakeFiles/back_up_action_bt_node.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
---
Failed   <<< behavior_tree [9.50s, exited with code 2]

Summary: 0 packages finished [9.96s]
  1 package failed: behavior_tree
  1 package had stderr output: behavior_tree

**Comment by duyongquan** [comment]
需要安装behaviortree-cpp， 运行命令行：sudo apt install ros-galactic-behaviortree-cpp-v3
